#!/usr/bin/env sh

stow --dotfiles \
     bat        \
     eza        \
     ghostty    \
     git        \
     lazygit    \
     ripgrep    \
     shell      \
     tmux       \
     zoxide || exit 1
